import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';

export interface ReportOptions {
  title: string;
  filename: string;
  columns: string[];
  data: any[];
  dateRange?: {
    start: string;
    end: string;
  };
  logo?: string;
  includeMetadata?: boolean;
}

export class ReportingService {
  private static isGenerating = false;

  // Format date to a friendly format with time
  private static formatDate(date: string | Date): string {
    const d = new Date(date);
    return d.toLocaleString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true
    });
  }

  // Format date for filename (YYYY-MM-DD)
  private static getCurrentDateString(): string {
    return new Date().toISOString().split('T')[0];
  }

  // Format date for display in reports
  private static formatDateForDisplay(date: string | Date): string {
    const d = new Date(date);
    return d.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  }

  // Generate filename with date range
  private static generateFilename(baseName: string, startDate?: string, endDate?: string): string {
    if (startDate && endDate) {
      const start = new Date(startDate).toISOString().split('T')[0];
      const end = new Date(endDate).toISOString().split('T')[0];
      return `${baseName}_${start}_${end}`;
    }
    return `${baseName}_${this.getCurrentDateString()}`;
  }

  // Export to PDF
  static async exportToPDF(options: ReportOptions): Promise<void> {
    if (this.isGenerating) return;
    this.isGenerating = true;

    try {
      const doc = new jsPDF('landscape', 'mm', 'a4');
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();

      // Header
      doc.setFontSize(20);
      doc.setTextColor(0, 122, 255);
      doc.text(options.title, pageWidth / 2, 20, { align: 'center' });

      // Subtitle with date
      doc.setFontSize(10);
      doc.setTextColor(100);
      const dateStr = `Generated: ${new Date().toLocaleString()}`;
      doc.text(dateStr, pageWidth / 2, 28, { align: 'center' });

      if (options.dateRange) {
        const startFormatted = this.formatDateForDisplay(options.dateRange.start);
        const endFormatted = this.formatDateForDisplay(options.dateRange.end);
        doc.text(
          `Period: ${startFormatted} to ${endFormatted}`,
          pageWidth / 2,
          34,
          { align: 'center' }
        );
      }

      // Metadata
      if (options.includeMetadata) {
        doc.setFontSize(8);
        doc.setTextColor(150);
        const metadata = [
          `Report Type: ${options.title}`,
          `Total Records: ${options.data.length}`,
          `Generated By: Solvertia Novarum Admin`,
          `Timestamp: ${new Date().toISOString()}`
        ];
        doc.text(metadata.join(' | '), 14, 40);
      }

      // Table
      const startY = options.includeMetadata ? 48 : 40;
      const tableData = options.data.map(item => 
        options.columns.map(col => {
          const value = col.split('.').reduce((obj, key) => obj?.[key], item);
          
          if (col === 'created_at' || col === 'updated_at' || col.includes('date')) {
            return value ? this.formatDate(value) : '-';
          }
          
          if (Array.isArray(value)) {
            return value.join(', ');
          }
          
          return value !== undefined && value !== null ? String(value) : '-';
        })
      );

      autoTable(doc, {
        head: [options.columns.map(col => {
          const name = col.split('.').pop() || col;
          return name.replace(/_/g, ' ').toUpperCase();
        })],
        body: tableData,
        startY: startY,
        theme: 'striped',
        headStyles: {
          fillColor: [0, 122, 255],
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          fontSize: 9,
        },
        bodyStyles: {
          fontSize: 8,
        },
        alternateRowStyles: {
          fillColor: [240, 248, 255],
        },
        margin: { top: 10, left: 14, right: 14 },
        didDrawPage: (data: any) => {
          const pageCount = doc.getNumberOfPages();
          const currentPage = doc.getCurrentPageInfo().pageNumber;
          doc.setFontSize(8);
          doc.setTextColor(150);
          doc.text(
            `Page ${currentPage} of ${pageCount}`,
            pageWidth / 2,
            pageHeight - 10,
            { align: 'center' }
          );
          doc.text(
            `Confidential - Solvertia Novarum Ltd`,
            pageWidth - 20,
            pageHeight - 10,
            { align: 'right' }
          );
        },
      });

      // Generate filename with date range
      const filename = this.generateFilename(
        options.filename,
        options.dateRange?.start,
        options.dateRange?.end
      );
      doc.save(`${filename}.pdf`);
    } finally {
      this.isGenerating = false;
    }
  }

  // Export to Excel
  static async exportToExcel(options: ReportOptions): Promise<void> {
    if (this.isGenerating) return;
    this.isGenerating = true;

    try {
      const data = options.data.map(item => {
        const row: any = {};
        options.columns.forEach(col => {
          const value = col.split('.').reduce((obj, key) => obj?.[key], item);
          const colName = col.split('.').pop() || col;
          
          if (col === 'created_at' || col === 'updated_at' || col.includes('date')) {
            row[colName] = value ? this.formatDate(value) : '-';
          } else if (Array.isArray(value)) {
            row[colName] = value.join(', ');
          } else {
            row[colName] = value !== undefined && value !== null ? value : '-';
          }
        });
        return row;
      });

      const wb = XLSX.utils.book_new();
      const ws = XLSX.utils.json_to_sheet(data);

      const colWidths: number[] = [];
      options.columns.forEach((col, index) => {
        const colName = col.split('.').pop() || col;
        const maxLength = Math.max(
          colName.length,
          ...data.map(row => String(row[colName] || '-').length)
        );
        colWidths[index] = Math.min(Math.max(maxLength + 2, 15), 50);
      });
      ws['!cols'] = colWidths.map(w => ({ wch: w }));

      XLSX.utils.book_append_sheet(wb, ws, options.title);
      
      const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
      const blob = new Blob([wbout], { type: 'application/octet-stream' });
      
      const filename = this.generateFilename(
        options.filename,
        options.dateRange?.start,
        options.dateRange?.end
      );
      saveAs(blob, `${filename}.xlsx`);
    } finally {
      this.isGenerating = false;
    }
  }

  // Export to CSV
  static async exportToCSV(options: ReportOptions): Promise<void> {
    if (this.isGenerating) return;
    this.isGenerating = true;

    try {
      const headers = options.columns.map(col => {
        const name = col.split('.').pop() || col;
        return name.replace(/_/g, ' ').toUpperCase();
      });
      
      const rows = options.data.map(item => 
        options.columns.map(col => {
          const value = col.split('.').reduce((obj, key) => obj?.[key], item);
          
          if (col === 'created_at' || col === 'updated_at' || col.includes('date')) {
            return value ? this.formatDate(value) : '-';
          }
          
          if (Array.isArray(value)) {
            return value.join(', ');
          }
          
          return value !== undefined && value !== null ? String(value) : '-';
        })
      );

      let csvContent = headers.join(',') + '\n';
      rows.forEach(row => {
        const escapedRow = row.map(cell => {
          if (typeof cell === 'string' && (cell.includes(',') || cell.includes('"') || cell.includes('\n'))) {
            return `"${cell.replace(/"/g, '""')}"`;
          }
          return cell;
        });
        csvContent += escapedRow.join(',') + '\n';
      });

      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      
      const filename = this.generateFilename(
        options.filename,
        options.dateRange?.start,
        options.dateRange?.end
      );
      saveAs(blob, `${filename}.csv`);
    } finally {
      this.isGenerating = false;
    }
  }

  // Export to Word (DOCX via HTML)
  static async exportToWord(options: ReportOptions): Promise<void> {
    if (this.isGenerating) return;
    this.isGenerating = true;

    try {
      const columns = options.columns.map(col => {
        const name = col.split('.').pop() || col;
        return name.replace(/_/g, ' ').toUpperCase();
      });
      
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="UTF-8">
          <title>${options.title}</title>
          <style>
            body {
              font-family: 'Times New Roman', Times, serif;
              margin: 40px;
              color: #333;
            }
            .header {
              text-align: center;
              border-bottom: 2px solid #007aff;
              padding-bottom: 20px;
              margin-bottom: 30px;
            }
            .header h1 {
              color: #007aff;
              font-size: 24px;
              margin: 0;
            }
            .header .subtitle {
              color: #666;
              font-size: 12px;
              margin-top: 5px;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 20px;
              font-size: 12px;
            }
            th {
              background-color: #007aff;
              color: white;
              padding: 10px;
              text-align: left;
              border: 1px solid #007aff;
            }
            td {
              padding: 8px 10px;
              border: 1px solid #ddd;
            }
            tr:nth-child(even) {
              background-color: #f8f9fa;
            }
            .footer {
              margin-top: 30px;
              text-align: center;
              font-size: 10px;
              color: #999;
              border-top: 1px solid #ddd;
              padding-top: 20px;
            }
            .metadata {
              font-size: 10px;
              color: #666;
              margin: 10px 0;
              text-align: center;
            }
            .watermark {
              color: #ddd;
              font-size: 40px;
              text-align: center;
              opacity: 0.3;
              position: fixed;
              top: 50%;
              left: 50%;
              transform: translate(-50%, -50%) rotate(-45deg);
              font-weight: bold;
              pointer-events: none;
              z-index: 0;
            }
          </style>
        </head>
        <body>
          <div class="watermark">CONFIDENTIAL</div>
          <div class="header">
            <h1>${options.title}</h1>
            <div class="subtitle">Generated: ${new Date().toLocaleString()}</div>
            ${options.dateRange ? `<div class="subtitle">Period: ${this.formatDateForDisplay(options.dateRange.start)} to ${this.formatDateForDisplay(options.dateRange.end)}</div>` : ''}
            ${options.includeMetadata ? `<div class="metadata">Total Records: ${options.data.length} | Solvertia Novarum Ltd</div>` : ''}
          </div>

          <table>
            <thead>
              <tr>
                ${columns.map(col => `<th>${col}</th>`).join('')}
              </tr>
            </thead>
            <tbody>
              ${options.data.map(item => `
                <tr>
                  ${options.columns.map(col => {
                    const value = col.split('.').reduce((obj, key) => obj?.[key], item);
                    let displayValue = '-';
                    
                    if (value !== undefined && value !== null) {
                      if (col === 'created_at' || col === 'updated_at' || col.includes('date')) {
                        displayValue = this.formatDate(value);
                      } else if (Array.isArray(value)) {
                        displayValue = value.join(', ');
                      } else {
                        displayValue = String(value);
                      }
                    }
                    
                    return `<td>${displayValue}</td>`;
                  }).join('')}
                </tr>
              `).join('')}
            </tbody>
          </table>

          <div class="footer">
            <p>Confidential - Solvertia Novarum Ltd</p>
            <p>Generated on ${new Date().toISOString()}</p>
          </div>
        </body>
        </html>
      `;

      const blob = new Blob([htmlContent], { 
        type: 'application/msword;charset=utf-8' 
      });
      
      const filename = this.generateFilename(
        options.filename,
        options.dateRange?.start,
        options.dateRange?.end
      );
      saveAs(blob, `${filename}.doc`);
    } finally {
      this.isGenerating = false;
    }
  }

  // Generate multiple reports
  static async generateReportBundle(
    reports: ReportOptions[],
    format: 'pdf' | 'excel' | 'csv' | 'word'
  ): Promise<void> {
    if (this.isGenerating) return;
    this.isGenerating = true;

    try {
      for (const report of reports) {
        switch (format) {
          case 'pdf':
            await this.exportToPDF(report);
            break;
          case 'excel':
            await this.exportToExcel(report);
            break;
          case 'csv':
            await this.exportToCSV(report);
            break;
          case 'word':
            await this.exportToWord(report);
            break;
        }
      }
    } finally {
      this.isGenerating = false;
    }
  }
}

export default ReportingService;
